# Generated by Django 4.1.6 on 2023-03-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='MyAddress',
        ),
    ]
