# Generated by Django 4.1.6 on 2023-03-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_userprofile_myaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyAddress',
            new_name='EditProfile',
        ),
    ]
