# Generated by Django 4.1.6 on 2023-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_address_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_discout',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('name', 'address_line_1', 'address_line_2', 'city', 'phone', 'email', 'state', 'country')},
        ),
    ]
