# Generated by Django 4.1.6 on 2023-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_order_discout_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address_line_1', 'address_line_2')},
        ),
    ]
