# Generated by Django 4.1.6 on 2023-03-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
