# Generated by Django 4.1.6 on 2023-03-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_returned_order_return_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_reason',
        ),
    ]
