# Generated by Django 4.1.6 on 2024-05-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_is_returned_remove_order_return_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
    ]
